'use client'

import Link from 'next/link'
import Image from 'next/image'
import { motion, AnimatePresence } from 'framer-motion'
import { ArrowRight, Activity, ShieldCheck, Zap, ChevronDown } from 'lucide-react'
import { useState } from 'react'

const faqs = [
  {
    question: "How does Coolara prevent AI hallucinations in critical operations?",
    answer: "Coolara strictly separates deterministic telemetry and calculations from AI inference. All numbers, anomaly thresholds, and alerts are generated by deterministic TypeScript rules. The AI is only used to explain qualitative findings and recommend operational responses, never to invent metrics."
  },
  {
    question: "Can I simulate different disaster scenarios?",
    answer: "Yes, our built-in Simulator engine allows you to inject synthetic workloads, cooling inefficiencies, and ambient temperature spikes to see how the system predicts downstream effects before they occur in the real world."
  },
  {
    question: "What happens if the primary database goes down?",
    answer: "Coolara features a robust local fallback mechanism. If the main Supabase instance is unreachable, it seamlessly switches to a synthetic telemetry generator, ensuring operations teams always have a functional dashboard for drills and demos."
  },
  {
    question: "How do you handle security and data privacy?",
    answer: "All telemetry data is stored securely using row-level security (RLS). Server-side operations are handled via secure service roles, and no sensitive credentials are ever shipped to the browser. Your synthetic metrics remain entirely within your private environment."
  },
  {
    question: "Can the AI optimize my power usage effectively?",
    answer: "Absolutely! After running a simulation, the AI uses Gemini to provide actionable recommendations. It analyzes the deterministic results of the simulation and suggests practical ways to mitigate risks or reduce overall power and water consumption."
  }
]

function FAQItem({ question, answer }: { question: string, answer: string }) {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div className="border border-[#2b363c] rounded-[12px] bg-[#171d21] overflow-hidden">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full justify-between items-center p-[20px] text-left focus:outline-none"
      >
        <strong className="text-[16px] text-white font-medium">{question}</strong>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
        >
          <ChevronDown className="text-teal-400" size={20} />
        </motion.div>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: 'easeInOut' }}
          >
            <div className="px-[20px] pb-[20px] text-[#91a0a3] leading-relaxed text-[15px]">
              {answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

export default function LandingPage() {
  return (
    <main className="dark min-h-screen bg-[#101517] text-[#eef3f1] font-sans selection:bg-teal-500/30">
      
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-[#2b363c] bg-[#101517]/80 backdrop-blur-md">
        <div className="max-w-[1200px] mx-auto px-[24px] h-[72px] flex items-center justify-between">
          <div className="flex items-center gap-[12px]">
            <Image src="/logos/coolara-app-icon.svg" alt="Coolara Logo" width={32} height={32} />
            <strong className="text-[18px] font-bold tracking-wide">Coolara</strong>
          </div>
          <Link 
            href="/dashboard"
            className="flex items-center gap-[8px] bg-[#171d21] border border-[#2b363c] hover:bg-[#20292d] text-white px-[16px] py-[8px] rounded-full text-[13px] font-medium transition-colors"
          >
            Open Dashboard <ArrowRight size={14} />
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-[180px] pb-[100px] px-[24px] overflow-hidden">
        {/* Glowing background orbs */}
        <div className="absolute top-[20%] left-[50%] -translate-x-1/2 w-[600px] h-[400px] bg-teal-500/20 blur-[120px] rounded-full pointer-events-none" />
        
        <div className="max-w-[800px] mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <span className="inline-block py-[6px] px-[12px] bg-teal-500/10 text-teal-400 border border-teal-500/20 rounded-full text-[12px] font-bold uppercase tracking-widest mb-[24px]">
              Next-Gen Data Center Operations
            </span>
          </motion.div>
          
          <motion.h1 
            className="text-[52px] md:text-[68px] font-extrabold leading-[1.1] tracking-tight mb-[24px] text-white"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            Smarter infrastructure.<br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-emerald-300">
              Zero compromises.
            </span>
          </motion.h1>
          
          <motion.p 
            className="text-[18px] md:text-[20px] text-[#91a0a3] mb-[40px] leading-relaxed max-w-[600px] mx-auto"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            Coolara is the AI-powered sustainability guardian for your data center. Monitor telemetry, detect anomalies instantly, and simulate disaster scenarios with deterministic confidence.
          </motion.p>
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-[16px]"
          >
            <Link 
              href="/dashboard"
              className="flex items-center gap-[10px] bg-teal-500 hover:bg-teal-400 text-[#042f2b] px-[28px] py-[16px] rounded-full text-[15px] font-bold transition-all hover:scale-105 shadow-[0_0_30px_rgba(20,184,166,0.3)]"
            >
              Go to Dashboard <ArrowRight size={18} />
            </Link>
          </motion.div>

          {/* App Preview Image */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="mt-[60px] relative mx-auto max-w-[1000px] rounded-[16px] border border-[#2b363c] bg-[#171d21]/50 p-[8px] backdrop-blur-xl shadow-2xl"
          >
            <div className="absolute inset-0 bg-gradient-to-t from-[#101517] via-transparent to-transparent z-10 pointer-events-none rounded-[16px]"></div>
            <Image 
              src="/dashboard-preview-v2.png" 
              alt="Coolara Command Center Preview" 
              width={1000} 
              height={600} 
              className="rounded-[10px] w-full h-auto object-cover border border-[#2b363c]"
            />
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-[100px] px-[24px] max-w-[1200px] mx-auto relative z-10">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-[24px]">
          {[
            {
              icon: Activity,
              title: "Real-time Telemetry",
              description: "Monitor Total Power, PUE, WUE, and Server Temperatures with deterministic precision. Zero hallucination guarantee."
            },
            {
              icon: ShieldCheck,
              title: "Anomaly Detection",
              description: "Instantly detect when metrics deviate from the expected baseline. Get AI-powered explanations for likely factors."
            },
            {
              icon: Zap,
              title: "Scenario Simulator",
              description: "Inject synthetic workloads or cooling inefficiencies to simulate disaster recovery and optimize resource allocation."
            }
          ].map((feature, i) => (
            <motion.div 
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              className="p-[32px] rounded-[16px] bg-[#171d21] border border-[#2b363c] hover:border-teal-500/50 transition-colors group"
            >
              <div className="w-[48px] h-[48px] rounded-[12px] bg-teal-500/10 text-teal-400 grid place-items-center mb-[20px] group-hover:scale-110 transition-transform">
                <feature.icon size={24} />
              </div>
              <h3 className="text-[20px] font-bold text-white mb-[12px]">{feature.title}</h3>
              <p className="text-[#91a0a3] leading-relaxed text-[15px]">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-[100px] px-[24px] max-w-[800px] mx-auto relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-[40px]"
        >
          <h2 className="text-[36px] font-bold text-white mb-[16px]">Frequently Asked Questions</h2>
          <p className="text-[#91a0a3] text-[16px]">Everything you need to know about Coolara architecture.</p>
        </motion.div>
        
        <div className="flex flex-col gap-[12px]">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
            >
              <FAQItem question={faq.question} answer={faq.answer} />
            </motion.div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[#2b363c] py-[40px] text-center text-[#64748b] text-[13px] relative z-10">
        <p>© 2026 Coolara. Engineered for sustainable data centers.</p>
      </footer>
    </main>
  )
}
